// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetCallerPort() {
  return window['go']['main']['App']['GetCallerPort']();
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function Greeting(arg1) {
  return window['go']['main']['App']['Greeting'](arg1);
}

export function Initialize(arg1, arg2, arg3) {
  return window['go']['main']['App']['Initialize'](arg1, arg2, arg3);
}

export function IsCallerRunning() {
  return window['go']['main']['App']['IsCallerRunning']();
}
