// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteLocaldata(arg1) {
  return window['go']['main']['App']['DeleteLocaldata'](arg1);
}

export function GetLocaldataList() {
  return window['go']['main']['App']['GetLocaldataList']();
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function Initialize(arg1) {
  return window['go']['main']['App']['Initialize'](arg1);
}

export function LoadClientID() {
  return window['go']['main']['App']['LoadClientID']();
}

export function LoadForwardURL() {
  return window['go']['main']['App']['LoadForwardURL']();
}

export function LoadLocaldata(arg1) {
  return window['go']['main']['App']['LoadLocaldata'](arg1);
}

export function SaveForwardURL(arg1) {
  return window['go']['main']['App']['SaveForwardURL'](arg1);
}

export function SaveLocaldata(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveLocaldata'](arg1, arg2, arg3);
}
