// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {config} from '../models';
import {logger} from '../models';
import {caller} from '../models';

export function GetCallerPort():Promise<number>;

export function GetVersion():Promise<string>;

export function Greeting(arg1:string):Promise<string>;

export function Initialize(arg1:config.Config,arg2:logger.LoggerImpl,arg3:caller.ProcessService):Promise<void>;

export function IsCallerRunning():Promise<boolean>;
