// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {local} from '../models';
import {config} from '../models';

export function DeleteLocaldata(arg1:string):Promise<local.Response>;

export function GetLocaldataList():Promise<local.Response>;

export function GetVersion():Promise<string>;

export function Initialize(arg1:config.Config):Promise<void>;

export function LoadClientID():Promise<local.Response>;

export function LoadForwardURL():Promise<local.Response>;

export function LoadLocaldata(arg1:string):Promise<local.Response>;

export function SaveForwardURL(arg1:string):Promise<local.Response>;

export function SaveLocaldata(arg1:string,arg2:string,arg3:any):Promise<local.Response>;
