// This file is generated by Wails. Do not modify.

export namespace wails {
  export namespace bindings {
    export interface App {
      /**
       * 返回问候信息
       */
      Greeting(name: string): Promise<string>;
      /**
       * 返回应用版本
       */
      GetVersion(): Promise<string>;
    }
  }
}

// Helper function for calling Go methods
export function callGoMethod(methodName: string, ...args: any[]): Promise<any> {
  // @ts-ignore
  if (typeof window.Go === 'undefined') {
    throw new Error('Go runtime not initialized');
  }
  // @ts-ignore
  return window.Go bindings[methodName](...args);
}
